<?php
// Include configuration for database connection
require_once "../database/config.php";

// Define the relative path to the PDF uploads directory
// This MUST match the $upload_dir_public_url in your admin script
$upload_dir_public_url = '../uploads/admissions_pdfs/'; // Adjusted path for public page access

// Initialize variables with default values or placeholders
$settings = [
    // Main Section Content
    'admissions_section_title' => 'Admissions',
    'admissions_section_description' => 'Join our vibrant learning community. We welcome students who are eager to learn, grow, and contribute to our school’s legacy of excellence.',
    'admissions_section_enabled' => true, // NEW FIELD: Default to enabled

    // Admission Process Steps
    'admission_process_title' => 'Admission Process',
    'admission_process_json' => '[]',
    'admissions_process_enabled' => true, // NEW FIELD: Default to enabled

    // Important Dates
    'important_dates_title' => 'Important Dates - Academic Year 2024-25',
    'important_dates_json' => '[]',
    'important_dates_enabled' => true, // NEW FIELD: Default to enabled

    // Admissions Status & Application Details
    'is_admissions_open' => false, // Default to closed
    'application_start_date' => null,
    'application_end_date' => null,
    'application_link' => '#',
    'notes_on_admissions_status' => 'Admissions are currently closed. Please check back for the next academic year.',
    
    // PDF URLs and Text Content
    'admissions_details_pdf_url' => null,
    'admissions_criteria_pdf_url' => null,
    'admissions_details_text' => 'Detailed information about our admissions process will be provided here. This section might include eligibility criteria, application fees, required documents, and steps for international applicants.',
    'admissions_criteria_text' => 'Specific criteria for admission will be listed here. This could cover academic requirements, age limits for different grades, language proficiency requirements, and any entrance examinations.'
];

$admission_process_steps = [];
$important_dates_list = [];

// Fetch settings from the database
$sql_fetch = "SELECT * FROM admissions_settings WHERE id = 1";
if ($result_fetch = mysqli_query($link, $sql_fetch)) {
    if (mysqli_num_rows($result_fetch) == 1) {
        $fetched_settings = mysqli_fetch_assoc($result_fetch);
        foreach ($settings as $key => $default_value) {
            if (isset($fetched_settings[$key]) && $fetched_settings[$key] !== NULL) {
                // Special handling for boolean fields (including the new ones)
                if (in_array($key, ['is_admissions_open', 'admissions_section_enabled', 'admissions_process_enabled', 'important_dates_enabled'])) {
                    $settings[$key] = (bool)$fetched_settings[$key];
                } else {
                    $settings[$key] = $fetched_settings[$key];
                }
            }
        }

        // Decode JSON data for process steps
        $decoded_process = json_decode($settings['admission_process_json'], true);
        if (json_last_error() === JSON_ERROR_NONE && is_array($decoded_process)) {
            $admission_process_steps = $decoded_process;
        }

        // Decode JSON data for important dates
        $decoded_dates = json_decode($settings['important_dates_json'], true);
        if (json_last_error() === JSON_ERROR_NONE && is_array($decoded_dates)) {
            $important_dates_list = $decoded_dates;
        }
    }
    mysqli_free_result($result_fetch);
} else {
    // Log error, but for public display, fall back to defaults
    error_log("Error fetching admissions settings: " . mysqli_error($link));
}

// Format dates for display
$start_date_formatted = !empty($settings['application_start_date']) ? date('F j, Y', strtotime($settings['application_start_date'])) : 'N/A';
$end_date_formatted = !empty($settings['application_end_date']) ? date('F j, Y', strtotime($settings['application_end_date'])) : 'N/A';

// Close database connection
if ($link) mysqli_close($link);

// IMPORTANT: header.php and footer.php are included as per your original structure.
// The CSS below is designed to style the content generated BY THIS FILE,
// and WILL NOT alter the HTML or styling provided by 'footer.php'.
require_once '../header.php'; // Assumed to open <body> tag
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($settings['admissions_section_title']); ?> - Your School Name</title>
    <link href="https://fonts.googleapis.com/css2?family=Lora:wght@400;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        /* Modern Green & Teal Color Palette */
        :root {
            --primary-color: #00695C; /* Deep Teal Green */
            --secondary-color: #26A69A; /* Medium Teal */
            --accent-color: #8BC34A; /* Light Green for highlights/hover */
            --text-dark: #212121;
            --text-medium: #424242;
            --text-light: #757575;
            --bg-light: #F5F5F5; /* Very light grey for page background */
            --card-bg: #FFFFFF;
            --border-light: #E0E0E0;
            --shadow-light: 0 6px 20px rgba(0, 0, 0, 0.08);
            --shadow-hover: 0 10px 30px rgba(0, 0, 0, 0.15);

            /* Status Colors */
            --status-open-bg: #4CAF50; /* Green */
            --status-closed-bg: #F44336; /* Red */
        }

        body {
            font-family: 'Open Sans', sans-serif;
            background-color: var(--bg-light);
            color: var(--text-dark);
            line-height: 1.7;
            margin: 0;
            padding: 0;
            /* IMPORTANT: Removed display: flex from body to avoid affecting footer.php */
        }

        .container {
            max-width: 960px;
            width: 100%;
            margin: 60px auto; /* Centered with top/bottom margin */
            padding: 0 20px; /* Horizontal padding for smaller screens */
            box-sizing: border-box;
        }

        /* --- Global Section Styling --- */
        .section {
            background-color: var(--card-bg);
            border-radius: 12px;
            box-shadow: var(--shadow-light);
            padding: 40px;
            margin-bottom: 40px;
            transition: box-shadow 0.3s ease;
        }
        .section:last-child {
            margin-bottom: 60px; /* More space before footer content */
        }
        .section:hover {
            box-shadow: var(--shadow-hover);
        }
        .section h2 {
            font-family: 'Lora', serif;
            font-size: 2.5em;
            color: var(--primary-color);
            text-align: center;
            margin-top: 0;
            margin-bottom: 30px;
            position: relative;
            padding-bottom: 10px;
        }
        .section h2::after {
            content: '';
            position: absolute;
            left: 50%;
            bottom: 0;
            transform: translateX(-50%);
            width: 80px;
            height: 3px;
            background-color: var(--secondary-color);
            border-radius: 5px;
        }

        /* --- Header Section (within .container) --- */
        header {
            text-align: center;
            margin-bottom: 70px;
            padding: 0 20px;
        }

        header h1 {
            font-family: 'Lora', serif;
            font-size: 4em;
            color: var(--primary-color);
            margin-bottom: 20px;
            font-weight: 700;
            line-height: 1.2;
        }

        .header-description {
            font-size: 1.25em;
            color: var(--text-medium);
            max-width: 750px;
            margin: 0 auto;
            line-height: 1.7;
        }

        /* --- Admissions Status Section --- */
        .status-section {
            display: flex;
            flex-direction: column;
            align-items: center;
            text-align: center;
        }
        .status-section h2::after {
            display: none; /* Remove specific underline for this h2 if it doesn't fit */
        }
        .status-badge {
            display: inline-flex;
            align-items: center;
            padding: 15px 30px;
            border-radius: 50px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 25px;
            box-shadow: 0 4px 10px rgba(0,0,0,0.1);
            font-size: 1.1em;
            color: white;
            transition: transform 0.3s ease;
        }
        .status-badge:hover {
             transform: translateY(-3px);
        }
        .status-badge.open {
            background-color: var(--status-open-bg);
        }
        .status-badge.closed {
            background-color: var(--status-closed-bg);
        }
        .status-badge i {
            margin-right: 12px;
            font-size: 1.3em;
        }
        .status-dates p {
            margin: 8px 0;
            font-size: 1.1em;
            color: var(--text-dark);
            font-weight: 600;
        }
        .status-link {
            display: inline-block;
            margin-top: 30px;
            padding: 18px 35px;
            background: linear-gradient(45deg, var(--primary-color), var(--secondary-color));
            color: white;
            text-decoration: none;
            border-radius: 8px;
            font-weight: 600;
            font-size: 1.2em;
            transition: transform 0.3s ease, box-shadow 0.3s ease;
            box-shadow: 0 6px 20px rgba(0, 105, 92, 0.3); /* Shadow based on primary color */
            letter-spacing: 0.5px;
        }
        .status-link:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 25px rgba(0, 105, 92, 0.45);
        }
        .status-notes {
            margin-top: 30px;
            font-style: italic;
            color: var(--text-light);
            max-width: 650px;
            line-height: 1.8;
            font-size: 1em;
        }

        /* --- Admission Process Section --- */
        .process-list {
            list-style: none;
            padding: 0;
            display: grid;
            grid-template-columns: 1fr;
            gap: 25px;
        }
        @media (min-width: 768px) {
            .process-list {
                grid-template-columns: repeat(2, 1fr);
            }
        }
        @media (min-width: 1024px) {
            .process-list {
                grid-template-columns: repeat(3, 1fr);
            }
        }

        .process-step-item {
            background-color: var(--card-bg);
            border-radius: 10px;
            padding: 25px;
            display: flex;
            flex-direction: column;
            align-items: center;
            text-align: center;
            box-shadow: var(--shadow-light);
            transition: transform 0.3s ease, box-shadow 0.3s ease;
            height: 100%; /* Ensure equal height cards in grid */
        }
        .process-step-item:hover {
            transform: translateY(-8px);
            box-shadow: var(--shadow-hover);
        }
        .process-step-item .icon-wrapper {
            background-color: var(--secondary-color);
            border-radius: 50%; /* Circular icon background */
            width: 60px;
            height: 60px;
            display: flex;
            align-items: center;
            justify-content: center;
            margin-bottom: 20px;
            box-shadow: 0 4px 10px rgba(38, 166, 154, 0.4); /* Shadow based on secondary color */
        }
        .process-step-item .icon-wrapper svg,
        .process-step-item .icon-wrapper .fas {
            width: 28px;
            height: 28px;
            font-size: 28px;
            color: white;
            fill: white;
        }
        .process-step-item .content {
            flex-grow: 1;
        }
        .process-step-item h3 {
            font-family: 'Open Sans', sans-serif;
            font-size: 1.3em;
            color: var(--primary-color);
            margin-top: 0;
            margin-bottom: 10px;
            font-weight: 700;
        }
        .process-step-item p {
            font-size: 0.95em;
            color: var(--text-medium);
            margin: 0;
            line-height: 1.6;
        }

        /* --- Important Dates Section --- */
        .important-dates-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 25px;
        }
        .important-date-card {
            background-color: var(--card-bg);
            border-radius: 10px;
            padding: 25px;
            text-align: center;
            box-shadow: var(--shadow-light);
            transition: transform 0.3s ease, box-shadow 0.3s ease;
            display: flex;
            flex-direction: column;
            justify-content: center;
            height: 100%; /* Ensure equal height cards in grid */
        }
        .important-date-card:hover {
            transform: translateY(-8px);
            box-shadow: var(--shadow-hover);
        }
        .important-date-card strong {
            font-family: 'Open Sans', sans-serif;
            font-size: 1.5em;
            color: var(--primary-color);
            font-weight: 700;
            display: block;
            margin-bottom: 10px;
        }
        .important-date-card span {
            font-size: 1em;
            color: var(--text-medium);
            display: block;
            line-height: 1.6;
        }

        /* --- Document & Text Sections --- */
        .document-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
            gap: 30px;
            margin-top: 30px; /* Space from H2 */
        }
        .document-card-item, .text-card-item {
            /* Now these are just standard cards within a section, not specific structural elements */
            background-color: var(--card-bg); /* Redundant if parent is also card-bg */
            border-radius: 12px;
            padding: 30px;
            box-shadow: var(--shadow-light);
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }
        .document-card-item:hover, .text-card-item:hover {
            transform: translateY(-5px);
            box-shadow: var(--shadow-hover);
        }

        .document-card-item h3, .text-card-item h3 {
            font-family: 'Lora', serif;
            font-size: 1.8em;
            color: var(--primary-color);
            margin-top: 0;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 1px solid var(--border-light);
            text-align: left;
        }
        .pdf-link {
            display: inline-flex;
            align-items: center;
            background-color: var(--bg-light);
            padding: 12px 20px;
            border-radius: 8px;
            text-decoration: none;
            color: var(--primary-color);
            font-weight: 600;
            transition: background-color 0.3s ease, transform 0.2s ease, box-shadow 0.2s ease;
            margin-top: 15px;
            border: 1px solid var(--border-light);
        }
        .pdf-link:hover {
            background-color: var(--accent-color); /* Use accent color on hover */
            color: white; /* Text color becomes white */
            transform: translateY(-2px);
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            border-color: var(--accent-color);
        }
        .pdf-link:hover i {
            color: white; /* PDF icon also becomes white */
        }
        .pdf-link i {
            margin-right: 12px;
            color: var(--primary-color); /* Icon color before hover */
            font-size: 1.3em;
            transition: color 0.3s ease;
        }
        .no-file-message {
            font-style: italic;
            color: var(--text-light);
            font-size: 0.95em;
            margin-top: 10px;
        }
        .details-text-content, .criteria-text-content {
            margin-top: 15px;
            line-height: 1.8;
            color: var(--text-medium);
            font-size: 1em;
        }
        .details-text-content p, .criteria-text-content p {
            margin-bottom: 1em;
        }

        /* If a text-section only has one text-card-item */
        .text-section .text-card-item {
            margin-top: 30px; /* Space from H2 */
        }
        /* If multiple text sections exist, provide consistent spacing */
        .text-section + .text-section {
            margin-top: 40px;
        }


        /* --- Responsive Adjustments --- */
        @media (max-width: 992px) {
            .container {
                margin: 40px auto;
                padding: 0 15px;
            }
            .section {
                padding: 30px;
                margin-bottom: 30px;
            }
            header h1 {
                font-size: 3.2em;
            }
            .header-description {
                font-size: 1.1em;
            }
            .section h2 {
                font-size: 2em;
                margin-bottom: 25px;
            }
            .status-badge {
                padding: 12px 25px;
                font-size: 1em;
            }
            .status-link {
                padding: 15px 30px;
                font-size: 1.1em;
            }
            .process-step-item .icon-wrapper {
                width: 50px;
                height: 50px;
            }
            .process-step-item .icon-wrapper svg,
            .process-step-item .icon-wrapper .fas {
                width: 24px;
                height: 24px;
                font-size: 24px;
            }
            .important-date-card strong {
                font-size: 1.3em;
            }
            .document-card-item h3, .text-card-item h3 {
                font-size: 1.6em;
            }
        }

        @media (max-width: 768px) {
            .section h2 {
                text-align: center;
            }
            .section h2::after {
                left: 50%;
                transform: translateX(-50%);
            }
            header h1 {
                font-size: 2.8em;
            }
            .header-description {
                font-size: 1em;
            }
            .process-list {
                grid-template-columns: 1fr; /* Single column on smaller mobiles */
            }
            .important-dates-grid {
                grid-template-columns: 1fr;
            }
            .document-grid {
                grid-template-columns: 1fr;
            }
            .document-card-item, .text-card-item {
                padding: 25px;
            }
        }

        @media (max-width: 480px) {
            .section {
                padding: 20px;
                margin-bottom: 25px;
            }
            header h1 {
                font-size: 2.2em;
            }
            .header-description {
                font-size: 0.95em;
            }
            .section h2 {
                font-size: 1.6em;
                margin-bottom: 20px;
            }
            .status-badge {
                padding: 10px 20px;
                font-size: 0.9em;
            }
            .status-link {
                padding: 12px 25px;
                font-size: 1em;
            }
            .process-step-item {
                padding: 20px;
            }
            .process-step-item h3 {
                font-size: 1.2em;
            }
            .document-card-item h3, .text-card-item h3 {
                font-size: 1.4em;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <?php if ($settings['admissions_section_enabled']): ?>
            <header>
                <h1><?php echo htmlspecialchars($settings['admissions_section_title']); ?></h1>
                <p class="header-description"><?php echo nl2br(htmlspecialchars($settings['admissions_section_description'])); ?></p>
            </header>
        <?php endif; ?>

        <!-- Admission Application Status Section -->
        <section class="status-section section">
            <h2>Application Status</h2>
            <?php if ($settings['is_admissions_open']): ?>
                <div class="status-badge open">
                    <i class="fas fa-check-circle"></i> Admissions Open
                </div>
                <div class="status-dates">
                    <p><strong>Start Date:</strong> <?php echo htmlspecialchars($start_date_formatted); ?></p>
                    <p><strong>End Date:</strong> <?php echo htmlspecialchars($end_date_formatted); ?></p>
                </div>
                <?php if (!empty($settings['application_link']) && $settings['application_link'] !== '#'): ?>
                    <a href="<?php echo htmlspecialchars($settings['application_link']); ?>" target="_blank" rel="noopener noreferrer" class="status-link">Apply Now <i class="fas fa-external-link-alt"></i></a>
                <?php endif; ?>
                <?php if (!empty($settings['notes_on_admissions_status'])): ?>
                    <p class="status-notes"><?php echo nl2br(htmlspecialchars($settings['notes_on_admissions_status'])); ?></p>
                <?php endif; ?>
            <?php else: ?>
                <div class="status-badge closed">
                    <i class="fas fa-times-circle"></i> Admissions Closed
                </div>
                <p class="status-notes"><?php echo nl2br(htmlspecialchars($settings['notes_on_admissions_status'])); ?></p>
            <?php endif; ?>
        </section>

        <!-- Admission Process Steps Section -->
        <?php if ($settings['admissions_process_enabled'] && (!empty($settings['admission_process_title']) || !empty($admission_process_steps))): ?>
            <section class="section">
                <h2><?php echo htmlspecialchars($settings['admission_process_title']); ?></h2>
                <?php if (!empty($admission_process_steps)): ?>
                    <ul class="process-list">
                        <?php foreach ($admission_process_steps as $step): ?>
                            <li class="process-step-item">
                                <?php if (!empty($step['icon'])): ?>
                                    <div class="icon-wrapper">
                                        <?php echo $step['icon']; // Assuming SVG output, ensure it's sanitized at admin input ?>
                                    </div>
                                <?php else: ?>
                                     <div class="icon-wrapper"><i class="fas fa-question-circle"></i></div>
                                <?php endif; ?>
                                <div class="content">
                                    <h3><?php echo htmlspecialchars($step['title'] ?? ''); ?></h3>
                                    <p><?php echo nl2br(htmlspecialchars($step['description'] ?? '')); ?></p>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php else: ?>
                    <p style="text-align: center; color: var(--text-light); margin-top: 20px;">Admission process steps are not yet defined.</p>
                <?php endif; ?>
            </section>
        <?php endif; ?>

        <!-- Important Dates Section -->
        <?php if ($settings['important_dates_enabled'] && (!empty($settings['important_dates_title']) || !empty($important_dates_list))): ?>
            <section class="section important-dates-section">
                <h2><?php echo htmlspecialchars($settings['important_dates_title']); ?></h2>
                <?php if (!empty($important_dates_list)): ?>
                    <div class="important-dates-grid">
                        <?php foreach ($important_dates_list as $date_item): ?>
                            <div class="important-date-card">
                                <strong><?php echo htmlspecialchars($date_item['date_text'] ?? ''); ?></strong>
                                <span><?php echo nl2br(htmlspecialchars($date_item['description'] ?? '')); ?></span>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php else: ?>
                    <p style="text-align: center; color: var(--text-light); margin-top: 20px;">Important dates are not yet announced.</p>
                <?php endif; ?>
            </section>
        <?php endif; ?>

        <!-- Admission Documents (PDF) Section -->
        <?php
        $show_document_section = !empty($settings['admissions_details_pdf_url']) || !empty($settings['admissions_criteria_pdf_url']);
        if ($show_document_section):
        ?>
            <section class="section">
                <h2>Admission Documents</h2>
                <div class="document-grid">
                    <div class="document-card-item">
                        <h3>Admission Details</h3>
                        <?php if (!empty($settings['admissions_details_pdf_url'])): ?>
                            <a href="<?php echo htmlspecialchars($upload_dir_public_url . $settings['admissions_details_pdf_url']); ?>" target="_blank" rel="noopener noreferrer" class="pdf-link">
                                <i class="fas fa-file-pdf"></i> Download Details PDF
                            </a>
                        <?php else: ?>
                            <p class="no-file-message">No Admission Details PDF uploaded.</p>
                        <?php endif; ?>
                    </div>
                    <div class="document-card-item">
                        <h3>Admission Criteria</h3>
                        <?php if (!empty($settings['admissions_criteria_pdf_url'])): ?>
                            <a href="<?php echo htmlspecialchars($upload_dir_public_url . $settings['admissions_criteria_pdf_url']); ?>" target="_blank" rel="noopener noreferrer" class="pdf-link">
                                <i class="fas fa-file-pdf"></i> Download Criteria PDF
                            </a>
                        <?php else: ?>
                            <p class="no-file-message">No Admission Criteria PDF uploaded.</p>
                        <?php endif; ?>
                    </div>
                </div>
            </section>
        <?php endif; ?>

        <!-- Admission Details (Text) Section -->
        <?php
        $show_details_text_section = !empty($settings['admissions_details_text']) && $settings['admissions_details_text'] !== 'Detailed information about our admissions process will be provided here. This section might include eligibility criteria, application fees, required documents, and steps for international applicants.';
        // Only show if content is not just the default placeholder
        if ($show_details_text_section):
        ?>
            <section class="section">
                <h2>Admission Details</h2>
                <div class="text-card-item">
                    <h3>General Information</h3>
                    <div class="details-text-content">
                        <?php echo nl2br(htmlspecialchars($settings['admissions_details_text'])); ?>
                    </div>
                </div>
            </section>
        <?php endif; ?>

        <!-- Admission Criteria (Text) Section -->
        <?php
        $show_criteria_text_section = !empty($settings['admissions_criteria_text']) && $settings['admissions_criteria_text'] !== 'Specific criteria for admission will be listed here. This could cover academic requirements, age limits for different grades, language proficiency requirements, and any entrance examinations.';
        // Only show if content is not just the default placeholder
        if ($show_criteria_text_section):
        ?>
            <section class="section">
                <h2>Admission Criteria</h2>
                <div class="text-card-item">
                    <h3>Eligibility & Requirements</h3>
                    <div class="criteria-text-content">
                        <?php echo nl2br(htmlspecialchars($settings['admissions_criteria_text'])); ?>
                    </div>
                </div>
            </section>
        <?php endif; ?>

    </div>
</body>
</html>

<?php
require_once '../footer.php'; // Assumed to close </body> and <html> tags
?>